server.port=8081
spring.application.name=ms-roles

spring.datasource.url=jdbc:oracle:thin:@bbddcloudnative_low?TNS_ADMIN=/app/wallet
spring.datasource.username=admin
spring.datasource.password=xcWy34mQR9SB!!p
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

azure.eventgrid.topic.endpoint=${AZURE_EVENT_GRID_TOPIC_ENDPOINT:http://host.docker.internal:7071/runtime/webhooks/EventGrid?functionName=RoleNotification}
azure.eventgrid.topic.key=${AZURE_EVENT_GRID_TOPIC_KEY:local_test_key}
