server.port=8080
spring.application.name=bff

# Microservicios Spring Boot
services.ms-roles.url=http://ms-roles:8081
services.ms-auth.url=http://ms-auth:8082
services.ms-biblioteca.url=http://ms-biblioteca:8083

# Funciones Serverless Azure (host.docker.internal apunta a tu Mac desde Docker)
azure.function.base-url=http://host.docker.internal:7071/api
